name: hot_dust
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - dask
  - dvc
  - hvplot
  - ipykernel
  - netcdf4
  - scipy
  - tensorflow
  - xarray
  - xarray-datatree
platforms:
  - linux-64
  - win-64
